//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeSkladistem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UpraljanjeSkladistemEntities : DbContext
    {
        public UpraljanjeSkladistemEntities()
            : base("name=UpraljanjeSkladistemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Materijal> Materijal { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<Stavka_narudzbenice> Stavka_narudzbenice { get; set; }
        public virtual DbSet<Narudzbenica> Narudzbenica { get; set; }
    }
}
