//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjePoslovnimPartnerima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int partnerId { get; set; }
        public string ime { get; set; }
        public string OIB { get; set; }
        public string adresa { get; set; }
        public string tip_partnera { get; set; }
    
        public virtual Tip_partnera Tip_partnera1 { get; set; }
    }
}
