//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzdavanjeRacuna
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faze_projekta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faze_projekta()
        {
            this.Faza_ima_materijal = new HashSet<Faza_ima_materijal>();
        }
    
        public int id { get; set; }
        public int projektId { get; set; }
        public int fazaId { get; set; }
        public byte zakljucano { get; set; }
    
        public virtual Faza Faza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faza_ima_materijal> Faza_ima_materijal { get; set; }
        public virtual Projekt Projekt { get; set; }
    }
}
