//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrikazStatistike
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka_primke
    {
        public int primkaId { get; set; }
        public int materijalId { get; set; }
        public int kolicina { get; set; }
    
        public virtual Materijal Materijal { get; set; }
        public virtual Primka Primka { get; set; }
    }
}
